FROM node:10.15.2

# Server
COPY ./server/package.json ./server/package-lock.json /home/node/app/
WORKDIR /home/node/app
RUN npm install --no-progress; \
  npm install --no-progress -g nodemon

# Front
COPY ./web/package.json ./web/package-lock.json /home/node/app/web/
WORKDIR /home/node/app/web
RUN npm install --no-progress

COPY ./server /home/node/app

# Frontend
WORKDIR /home/node/app/web
COPY ./web /home/node/app/web
RUN npm run build

WORKDIR /home/node/app

CMD [ "npm", "run", "serve" ]
