FROM node:10.15.2

# Front
COPY ./web/package.json ./web/package-lock.json /app/web/
WORKDIR /app/web
RUN npm install --no-progress

# Server
COPY ./server/package.json ./server/package-lock.json /app/
WORKDIR /app
RUN npm install --no-progress; \
  npm install --no-progress -g nodemon

COPY ./server /app

# Frontend
WORKDIR /app/web
COPY ./web /app/web
RUN npm run build

EXPOSE 3000

WORKDIR /app
CMD [ "npm", "start" ]
