<template>
  <!-- eslint-disable -->
  <el-dialog
    title="Terms and Conditions"
    :visible="show"
    @close="$emit('update:show', false)"
  >
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Eget arcu dictum varius duis at. Cursus in hac habitasse platea. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Enim tortor at auctor urna nunc. Elit scelerisque mauris pellentesque pulvinar. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. At elementum eu facilisis sed odio morbi quis commodo odio. Feugiat in ante metus dictum. Suscipit tellus mauris a diam. Semper viverra nam libero justo. Pellentesque pulvinar pellentesque habitant morbi. Egestas purus viverra accumsan in nisl nisi.</p>
    <p>Nec dui nunc mattis enim ut tellus elementum. Porttitor leo a diam sollicitudin. Nisl vel pretium lectus quam id leo in vitae. Ac placerat vestibulum lectus mauris ultrices. Dictum varius duis at consectetur. Cursus risus at ultrices mi tempus. In est ante in nibh mauris cursus mattis molestie. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Viverra mauris in aliquam sem fringilla. Aliquam sem fringilla ut morbi tincidunt. Semper auctor neque vitae tempus quam. Est velit egestas dui id ornare arcu odio ut sem. Duis convallis convallis tellus id. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Congue quisque egestas diam in arcu cursus euismod quis. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Feugiat scelerisque varius morbi enim.</p>
    <p>Ornare massa eget egestas purus viverra accumsan in nisl. In est ante in nibh mauris cursus mattis. Porttitor eget dolor morbi non arcu. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Habitant morbi tristique senectus et netus et malesuada fames. Urna id volutpat lacus laoreet. Magna ac placerat vestibulum lectus mauris ultrices eros. Elementum nisi quis eleifend quam adipiscing. Suscipit adipiscing bibendum est ultricies integer quis. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id.</p>
    <p>Arcu cursus vitae congue mauris rhoncus. Porttitor massa id neque aliquam. Tincidunt vitae semper quis lectus nulla. Diam vulputate ut pharetra sit amet. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. A lacus vestibulum sed arcu non odio. Vestibulum sed arcu non odio. Ullamcorper a lacus vestibulum sed arcu non. Et sollicitudin ac orci phasellus egestas tellus. Nibh cras pulvinar mattis nunc. Quisque id diam vel quam elementum pulvinar etiam. Diam donec adipiscing tristique risus nec feugiat.</p>
    <p>At volutpat diam ut venenatis tellus in metus vulputate. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Eu augue ut lectus arcu bibendum at varius vel. Aliquam id diam maecenas ultricies mi eget. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Ullamcorper a lacus vestibulum sed arcu. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Sed sed risus pretium quam vulputate dignissim suspendisse. Congue eu consequat ac felis. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere.</p>
    <p>Sagittis purus sit amet volutpat. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Amet nisl suscipit adipiscing bibendum. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Elit at imperdiet dui accumsan sit amet nulla facilisi. Tellus at urna condimentum mattis pellentesque id. Vitae justo eget magna fermentum. Urna molestie at elementum eu facilisis sed. Sed vulputate mi sit amet mauris. Augue eget arcu dictum varius duis at.</p>
    <p>Vel orci porta non pulvinar neque. Fringilla ut morbi tincidunt augue interdum velit. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Venenatis tellus in metus vulputate eu scelerisque. Aliquam ut porttitor leo a diam sollicitudin. Sed blandit libero volutpat sed cras ornare arcu dui. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Lectus mauris ultrices eros in. Suspendisse sed nisi lacus sed viverra tellus.</p>
    <p>Maecenas accumsan lacus vel facilisis volutpat est velit. Vulputate ut pharetra sit amet aliquam id diam. Amet nulla facilisi morbi tempus iaculis urna id. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Volutpat diam ut venenatis tellus in metus. Enim sit amet venenatis urna cursus eget. Netus et malesuada fames ac turpis. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Maecenas pharetra convallis posuere morbi leo urna molestie at. Vestibulum sed arcu non odio euismod lacinia. Fermentum et sollicitudin ac orci phasellus. Porttitor massa id neque aliquam vestibulum morbi. Faucibus turpis in eu mi bibendum. Duis at consectetur lorem donec massa sapien. Nulla aliquet enim tortor at auctor urna nunc id. Dui nunc mattis enim ut. Nec feugiat nisl pretium fusce. Orci ac auctor augue mauris augue. Sed libero enim sed faucibus.</p>
    <p>Quam viverra orci sagittis eu volutpat odio facilisis. Posuere urna nec tincidunt praesent. Velit sed ullamcorper morbi tincidunt. Dictum sit amet justo donec enim diam. Et tortor consequat id porta. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Fames ac turpis egestas maecenas pharetra convallis. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Placerat duis ultricies lacus sed turpis tincidunt id aliquet risus. Nunc sed augue lacus viverra vitae congue. Nibh mauris cursus mattis molestie a. Donec massa sapien faucibus et molestie ac. Ac tortor dignissim convallis aenean et tortor at. Fames ac turpis egestas integer eget aliquet nibh praesent. Habitant morbi tristique senectus et. Sollicitudin ac orci phasellus egestas. Feugiat nisl pretium fusce id.</p>
    <p>Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Nunc sed blandit libero volutpat sed. Gravida neque convallis a cras semper auctor neque vitae tempus. Senectus et netus et malesuada fames ac turpis egestas. Commodo odio aenean sed adipiscing. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Nibh tortor id aliquet lectus. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Elit sed vulputate mi sit amet mauris commodo quis. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Sit amet porttitor eget dolor. Leo integer malesuada nunc vel. Nunc mi ipsum faucibus vitae.</p>
  </el-dialog>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  name: 'ToS',

  props: {
    show: { type: Boolean, required: true },
  },
});
</script>
