version: '3.7'
services:
  node:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-server
    user: node
    # depends_on:
    #   - mongodb
    ports:
      - "3000:3000"
    volumes:
      - type: bind # Server files
        source: ../server
        target: /app
      - type: bind # Server files
        source: ../web
        target: /app/web
      - /app/node_modules # Keep the image's folder
      - /app/web/node_modules # Keep the image's folder
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: calories
      MONGO_USER: root
      MONGO_PASSWORD: pwd123

  mongodb:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-mongo
    volumes:
      - type: bind
        source: ./
        target: /usr/docker
