FROM cal-web-deps:latest

COPY ./server /home/node/app

# Frontend
WORKDIR /home/node/app/web
COPY ./web /home/node/app/web
RUN npm run build

EXPOSE 3000

WORKDIR /home/node/app
USER node
CMD [ "npm", "run", "serve" ]
